WebAutopark/Models/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebAutopark.Models
{
    public class OrderViewModel
    {
        [Required]
        public int OrderId { get; set; }

        [Required]
        public int VehicleId { get; set; }

        public List<OrderElementViewModel> OrderElements { get; set; }
    }
}

WebAutopark/Controllers/OrderController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using WebAutopark.BusinessLogicLayer.Interfaces;
using WebAutopark.Models;

namespace WebAutopark.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderDtoService;
        private readonly IOrderElementService _orderElementDtoService;
        private readonly IMapper _mapper;

        public OrderController(IOrderService orderDtoService,
                               IOrderElementService orderElementDtoService,
                               IMapper mapper)
        {
            _orderDtoService = orderDtoService;
            _orderElementDtoService = orderElementDtoService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var ordersDto = await _orderDtoService.GetAll();
            var ordersView = _mapper.Map<List<OrderViewModel>>(ordersDto);

            return View(ordersView);
        }


        [HttpGet]
        public async Task<IActionResult> Create(int vehicleId)
        {
            var order = await _orderDtoService.CreateAndReturn(vehicleId);

            return RedirectToAction("Create", "OrderElement", new { orderId = order.OrderId });
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmDelete(int orderId)
        {
            var orderDto = await _orderDtoService.GetById(orderId);

            if (orderDto != null)
            {
                var orderView = _mapper.Map<OrderViewModel>(orderDto);
                return View(orderView);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int orderId)
        {
            await _orderDtoService.Delete(orderId);

            return RedirectToAction(nameof(Index));
        }
    }
}

WebAutopark/Controllers/VehicleController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using WebAutopark.BusinessLogicLayer.DataTransferObjects;
using WebAutopark.BusinessLogicLayer.Interfaces;
using WebAutopark.Models;
using System;
using System.Linq;
using WebAutopark.Core.Enums;


namespace WebAutopark.Controllers
{
    public class VehicleController : Controller
    {
        private readonly IVehicleService _vehicleDtoService;
        private readonly IDataService<VehicleTypeDto> _vehicleTypeDtoService;
        private readonly IMapper _mapper;

        public VehicleController(IVehicleService vehicleDtoService,
                                 IDataService<VehicleTypeDto> vehicleTypeDtoService,
                                 IMapper mapper)
        {
            _vehicleDtoService = vehicleDtoService;
            _vehicleTypeDtoService = vehicleTypeDtoService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchName, SortOrder sortOrder)
        {
            ViewBag.SortByModel = sortOrder == SortOrder.ModelAsc ? SortOrder.ModelDesc : SortOrder.ModelAsc;
            ViewBag.SortByMileage = sortOrder == SortOrder.MileageAsc ? SortOrder.MileageDesc : SortOrder.MileageAsc;
            ViewBag.SortByType = sortOrder == SortOrder.TypeAsc ? SortOrder.TypeDesc : SortOrder.TypeAsc;

            ViewBag.CurrentSearchName = searchName;

            var vehiclesDto = await _vehicleDtoService.GetAll(sortOrder);

            if (!String.IsNullOrEmpty(searchName))
            {
                vehiclesDto = vehiclesDto.Where(v => v.Model
                    .Contains(searchName, StringComparison.OrdinalIgnoreCase));
            }

            var vehiclesView = _mapper.Map<List<VehicleViewModel>>(vehiclesDto);
            return View(vehiclesView);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Colors = Enum.GetValues(typeof(Color)).Cast<Color>();
            ViewBag.Types = await _vehicleTypeDtoService.GetAll();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(VehicleViewModel vehicleViewModel)
        {
            if (ModelState.IsValid)
            {
                var vehicleDto = _mapper.Map<VehicleDto>(vehicleViewModel);
                await _vehicleDtoService.Create(vehicleDto);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var vehicleDto = await _vehicleDtoService.GetById(id);

            if (vehicleDto != null)
            {
                var vehicleView = _mapper.Map<VehicleViewModel>(vehicleDto);
                return View(vehicleView);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _vehicleDtoService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var vehicleDto = await _vehicleDtoService.GetById(id);

            if (vehicleDto != null)
            {
                ViewBag.Colors = Enum.GetValues(typeof(Color))
                                     .Cast<Color>();

                ViewBag.Types = await _vehicleTypeDtoService.GetAll();
                var vehicleView = _mapper.Map<VehicleViewModel>(vehicleDto);
                return View(vehicleView);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VehicleViewModel vehicleViewModel)
        {
            if (ModelState.IsValid)
            {
                var vehicleDto = _mapper.Map<VehicleDto>(vehicleViewModel);
                await _vehicleDtoService.Update(vehicleDto);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Information(int id)
        {
            var vehicleDto = await _vehicleDtoService.GetById(id);
            var vehicleView = _mapper.Map<VehicleViewModel>(vehicleDto);

            return View(vehicleView);
        }
    }
}

WebAutopark/Views/Order/ConfirmDelete.cshtml
@model WebAutopark.Models.OrderViewModel
@{
    ViewData["Title"] = "Delete Order";
}
<h2>@ViewBag.Title</h2>
<div>
    <dl class="dl-horizontal">
        <dt>Id</dt>
        <dd>
            @Model.OrderId
        </dd>

        <dt>VehicleId</dt>
        <dd>
            @Model.VehicleId
        </dd>
    </dl>

    <div>
        <form asp-controller="Order" asp-action="Delete" asp-route-orderId="@Model.OrderId" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Delete" />
            </div>
        </form>
    </div>
</div>

WebAutopark/Views/Order/Index.cshtml
@model IEnumerable<WebAutopark.Models.OrderViewModel>

@{
    ViewData["Title"] = "ViewOrders";
}

<hr />
<h4 class="text-center my-1">Details list</h4>
<hr />
<table class="table table-striped table-borderless table-sm">
    <thead class="thead-light">
        <tr>
            <th>
                OrderId
            </th>
            <th>
                VehicleId
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.OrderId
                </td>
                <td>
                    @item.VehicleId
                </td>
                <td>
                    <a asp-controller="OrderElement" class="btn btn-outline-secondary" asp-action="Index" asp-route-orderId="@item.OrderId">Info</a> | 
                    <a asp-controller="Order" class="btn btn-outline-secondary" asp-action="ConfirmDelete" asp-route-orderId="@item.OrderId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebAutopark/Views/Order/OrderInformation.cshtml
@model WebAutopark.Models.OrderViewModel

@{
    ViewData["Title"] = "OrderInfo";
}
<h2>@ViewData["Title"]</h2>


<div>
    <div>
        <h6 class="d-inline-block">Order id:</h6>
        <p class="m-2 d-inline-block">@Model.OrderId</p>
    </div>

    <div>
        <h6 class="d-inline-block">For vehicle id:</h6>
        <p class="m-2 d-inline-block">@Model.VehicleId</p>
    </div>

    <div>
        <h6 class="d-inline-block">Date of creation:</h6>
        <p class="m-2 d-inline-block">@Model.Date</p>
    </div>
    <hr />
</div>

<hr />

<table class="table table-striped table-borderless table-sm">
    <thead class="thead-light">
        <tr>
            <th>
                OrderElementId
            </th>
            <th>
                DetailId
            </th>
            <th>
                DetailName
            </th>
            <th>
                Quantity
            </th>
        </tr>
    </thead>
    <tbody>
       @foreach (var item in Model.OrderElements)
        {
        <tr>
            <td>
                @item.OrderElementId
            </td>
            <td>
                @item.DetailId
            </td>
            <td>
                @item.Detail.DetailName
            </td>
            <td>    
                @item.Quantity
            </td>
        </tr>
        }
    </tbody>
</table>

<hr>

<a asp-controller="Order" class="btn btn-outline-secondary" asp-action="Index">Back to orders list</a>
<a asp-controller="Vehicle" class="btn btn-outline-secondary" asp-action="Information" asp-route-id="@Model.VehicleId">Back to vehicle</a>