WebAutopark/Models/VehicleTypeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAutopark.Models
{
    public class VehicleTypeViewModel
    {
        [Required]
        public int TypeId { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Max length: 50.")]
        public string TypeName { get; set; }

        [Required]
        [Range(0.5, 3, ErrorMessage = "Tax Coefficient must be from 0.5 to 3.0")]
        public double TaxCoefficient { get; set; }
    }
}

WebAutopark/Controllers/VehicleTypeController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using WebAutopark.BusinessLogicLayer.DataTransferObjects;
using WebAutopark.BusinessLogicLayer.Interfaces;
using WebAutopark.Models;

namespace WebAutopark.Controllers
{
    public class VehicleTypeController : Controller
    {
        private readonly IDataService<VehicleTypeDto> _vehicleTypeDtoService;
        private readonly IMapper _mapper;

        public VehicleTypeController(IDataService<VehicleTypeDto> dtoService, IMapper mapper)
        {
            _vehicleTypeDtoService = dtoService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var vehicleTypesDto = await _vehicleTypeDtoService.GetAll();
            var vehicleTypesView = _mapper.Map<List<VehicleTypeViewModel>>(vehicleTypesDto);
            return View(vehicleTypesView);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(VehicleTypeViewModel vehicleTypeViewModel)
        {
            if (ModelState.IsValid)
            {
                var vehicletypeDto = _mapper.Map<VehicleTypeDto>(vehicleTypeViewModel);
                await _vehicleTypeDtoService.Create(vehicletypeDto);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var vehicleType = await _vehicleTypeDtoService.GetById(id);

            if (vehicleType != null)
            {
                var vehicleTypeView = _mapper.Map<VehicleTypeViewModel>(vehicleType);
                return View(vehicleTypeView);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VehicleTypeViewModel vehicleTypeViewModel)
        {
            if (ModelState.IsValid)
            {
                var vehicleTypeDto = _mapper.Map<VehicleTypeDto>(vehicleTypeViewModel);
                await _vehicleTypeDtoService.Update(vehicleTypeDto);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var vehicleTypeDto = await _vehicleTypeDtoService.GetById(id);

            if (vehicleTypeDto != null)
            {
                var vehicleTypeView = _mapper.Map<VehicleTypeViewModel>(vehicleTypeDto);
                return View(vehicleTypeView);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _vehicleTypeDtoService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebAutopark/Views/VehicleType/ConfirmDelete.cshtml
@model WebAutopark.Models.VehicleTypeViewModel
@{
    ViewData["Title"] = "Delete VehicleType";
}
<h2>@ViewBag.Title</h2>
<div>
    <dl class="dl-horizontal">
        <dt>Id</dt>
        <dd>
            @Model.TypeId
        </dd>

        <dt>Name</dt>
        <dd>
            @Model.TypeName
        </dd>

        <dt>TaxCoefficient</dt>
        <dd>
            @Model.TaxCoefficient
        </dd>
    </dl>

    <div>
        <form asp-controller="VehicleType" asp-action="Delete" asp-route-id="@Model.TypeId" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Delete" />
            </div>
        </form>
    </div>
</div>

WebAutopark/Views/VehicleType/Create.cshtml
@model WebAutopark.Models.VehicleTypeViewModel

@{
    ViewData["Title"] = "New Type";
}
<h2>@ViewData["Title"]</h2>

<form asp-action="Create" asp-controller="VehicleType">
    <div>
        <div class="form-group">
            <label asp-for="TypeName"></label>
            <input asp-for="TypeName" class="form-control  form-control-sm" />
            <span asp-validation-for="TypeName" />
        </div>

        <div class="form-group">
            <label asp-for="TaxCoefficient"></label>
            <input asp-for="TaxCoefficient" class="form-control  form-control-sm" />
            <span asp-validation-for="TaxCoefficient" />
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-outline-secondary" />
        </div>
    </div>
</form>

<div>
    <a asp-controller="VehicleType" asp-action="Index">Back to the list</a>
</div>

WebAutopark/Views/VehicleType/Delete.cshtml
@model WebAutopark.Models.VehicleTypeViewModel
@{
    ViewData["Title"] = "Delete VehicleType";
}
<h2>@ViewBag.Title</h2>
<div>
    <dl class="dl-horizontal">
        <dt>Id</dt>
        <dd>
            @Model.TypeId
        </dd>

        <dt>Name</dt>
        <dd>
            @Model.TypeName
        </dd>

        <dt>TaxCoefficient</dt>
        <dd>
            @Model.TaxCoefficient
        </dd>
    </dl>

    <div>
        <form asp-controller="VehicleType" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Delete" />
            </div>
        </form>
    </div>
</div>

WebAutopark/Views/VehicleType/Edit.cshtml
@model WebAutopark.Models.VehicleTypeViewModel
@{
    ViewData["Title"] = "Update VehicleType";
}
<h2>@ViewData["Title"].</h2>

<form asp-action="Edit" asp-controller="VehicleType">
    <div>
        <input type="hidden" asp-for="TypeId" />
        <div class="form-group">
            <label asp-for="TypeName"></label>
            <input asp-for="TypeName" class="form-control  form-control-sm" />
            <span asp-validation-for="TypeName" />
        </div>

        <div class="form-group">
            <label asp-for="TaxCoefficient"></label>
            <input asp-for="TaxCoefficient" class="form-control  form-control-sm" />
            <span asp-validation-for="TaxCoefficient" />
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-outline-secondary" />
        </div>
    </div>
</form>

<div>
    <a asp-controller="VehicleType" asp-action="Index">Back to the list</a>
</div>

WebAutopark/Views/VehicleType/Index.cshtml
@model IEnumerable<WebAutopark.Models.VehicleTypeViewModel>

@{
    ViewData["Title"] = "ViewVehicleTypes";
}

<hr />
<h4 class="text-center my-1">Types list</h4>
<hr />
<table class="table table-striped table-borderless table-sm">
    <thead class="thead-light">
        <tr>
            <th>
                Id
            </th>
            <th>
                TypeName
            </th>
            <th>
                TaxCoefficient
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @item.TypeId
            </td>
            <td>
                @item.TypeName
            </td>
            <td>
                @item.TaxCoefficient
            </td>
            <td>
                <a asp-controller="VehicleType" asp-action="Edit" asp-route-id="@item.TypeId">Update</a> |
                <a asp-controller="VehicleType" asp-action="ConfirmDelete" asp-route-id="@item.TypeId">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>
<p>
    <a asp-controller="VehicleType" asp-action="Create">Add</a>
</p>