WebAutopark/Models/OrderElementViewModel.cs
    using System.ComponentModel.DataAnnotations;

namespace WebAutopark.Models
{
    public class OrderElementViewModel
    {
        [Required]
        public int OrderElementId { get; set; }

        [Required]
        public int OrderId { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Count can't be < 1.")]
        public int Quantity { get; set; }

        [Required]
        public int DetailId { get; set; }

        public DetailViewModel Detail { get; set; }
    }
}

WebAutopark/Controllers/OrderElementController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using WebAutopark.BusinessLogicLayer.Interfaces;
using WebAutopark.Models;
using WebAutopark.BusinessLogicLayer.DataTransferObjects;

namespace WebAutopark.Controllers
{
    public class OrderElementController : Controller
    {
        private readonly IOrderElementService _orderElementDtoService;
        private readonly IMapper _mapper;
        private readonly IDataService<DetailDto> _detailService;

        public OrderElementController(IOrderElementService orderElementService,
                                      IDataService<DetailDto> detailService,
                                      IMapper mapper)
        {
            _orderElementDtoService = orderElementService;
            _mapper = mapper;
            _detailService = detailService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int orderId)
        {
            var orderElements = await _orderElementDtoService.GetAll(orderId);
            var orderElementsView = _mapper.Map<List<OrderElementViewModel>>(orderElements);

            ViewBag.OrderId = orderId;

            return View(orderElementsView);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int orderElementId)
        {
            var orderElement = await _orderElementDtoService.GetById(orderElementId);
            var orderElementView = _mapper.Map<OrderElementViewModel>(orderElement);

            await SetupDetailsToViewBag();

            return View(orderElementView);
        }

        [HttpPost]
        public async Task<IActionResult> Update(OrderElementViewModel orderElementView)
        {
            if (ModelState.IsValid)
            {
                var orderElementDto = _mapper.Map<OrderElementDto>(orderElementView);
                await _orderElementDtoService.Update(orderElementDto);

                return RedirectToAction(nameof(Index), new { orderId = orderElementView.OrderId });
            }

            return RedirectToAction("Index", "Order");
        }

        [HttpGet]
        public async Task<IActionResult> Create(int orderId)
        {
            var orderElementView = new OrderElementViewModel { OrderId = orderId };
            await SetupDetailsToViewBag();

            return View(orderElementView);
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderElementViewModel orderElementView, bool createAnother)
        {
            if (ModelState.IsValid)
            {
                var orderElementDto = _mapper.Map<OrderElementDto>(orderElementView);
                await _orderElementDtoService.Create(orderElementDto);

                if (createAnother)
                    return RedirectToAction(nameof(Create), new { orderId = orderElementView.OrderId });
            }

            return RedirectToAction("Index", "Order");
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmDelete(int orderElementId)
        {
            var orderElementDto = await _orderElementDtoService.GetById(orderElementId);

            if (orderElementDto != null)
            {
                var orderElementView = _mapper.Map<OrderElementViewModel>(orderElementDto);
                return View(orderElementView);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int orderElementId, int orderId)
        {
            await _orderElementDtoService.Delete(orderElementId);
            return RedirectToAction(nameof(Index), new { orderId });
        }

        private async Task SetupDetailsToViewBag()
        {
            var detailsDto = await _detailService.GetAll();
            var detailsView = _mapper.Map<List<DetailViewModel>>(detailsDto);

            ViewBag.Details = detailsView;
        }
    }
}

WebAutopark/Views/OrderElement/ConfirmDelete.cshtml
@model WebAutopark.Models.OrderElementViewModel
@{
    ViewData["Title"] = "Delete orderElement";
}
<h2>@ViewBag.Title</h2>

<div>
    <div class="validation" asp-validation-summary="ModelOnly"></div>

    <div>
        <h6 class="d-inline-block">OrderElementId:</h6>
        <p class="m-2 d-inline-block">@Model.OrderElementId</p>
    </div> 

    <div>
        <form asp-controller="OrderElement" asp-action="Delete" asp-route-orderElementId="@Model.OrderElementId" asp-route-orderId="@Model.OrderId" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Delete" />
            </div>
        </form>
    </div>
</div>

WebAutopark/Views/OrderElement/Create.cshtml
@model WebAutopark.Models.OrderElementViewModel

@{
    ViewData["Title"] = "NewOrderElement";
}
<h2>@ViewData["Title"]</h2>

<form asp-action="Create" asp-controller="OrderElement">
    <div>
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <input type="hidden" asp-for="OrderId" />
        <div class="form-group">
            <label asp-for="DetailId"></label>
            <select class="form-select custom-select" asp-for="DetailId">
                @foreach (var detail in ViewBag.Details)
                {
                    <option value="@detail.DetailId">@detail.DetailName</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label asp-for="Quantity"></label>
            <input asp-for="Quantity" class="form-control form-control-sm" value="1"/>
            <span asp-validation-for="Quantity" />
        </div>
        <div class="form-group">
            <input class="form-check-input" type="checkbox" name="createAnother" id="flexCheckDefault" value="true"> 
            <label class="form-check-label" for="flexCheckDefault">
                Create Another
            </label>
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-outline-secondary" />
        </div>
    </div>
</form>

WebAutopark/Views/OrderElement/Index.cshtml
@model IEnumerable<WebAutopark.Models.OrderElementViewModel>

@{
    ViewData["Title"] = "OrderElementInfo";
}
<h2>@ViewData["Title"]</h2>

<table class="table table-striped table-borderless table-sm">
    <thead class="thead-light">
        <tr>
            <th>
                OrderId
            </th>
            <th>
                OrderElementId
            </th>
            <th>
                DetailId
            </th>
            <th>
                DetailName
            </th>
            <th>
                Quantity
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
       @foreach (var item in Model)
        {
        <tr>
            <td>
                @item.OrderId
            </td>
            <td>
                @item.OrderElementId
            </td>
            <td>
                @item.DetailId
            </td>
            <td>
                @item.Detail.DetailName
            </td>
            <td>    
                @item.Quantity
            </td>
            <td>
                <a asp-controller="OrderElement" class="btn btn-outline-secondary" asp-action="Update" asp-route-orderElementId="@item.OrderElementId">Udpate</a> |
                <a asp-controller="OrderElement" class="btn btn-outline-secondary" asp-action="ConfirmDelete" asp-route-orderElementId="@item.OrderElementId">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

<hr>
<a asp-controller="OrderElement" class="btn btn-outline-secondary" asp-action="Create" asp-route-orderId="@ViewBag.OrderId">Add</a> |
<a asp-controller="Order" class="btn btn-outline-secondary" asp-action="Index">Back to orders list</a>

WebAutopark/Views/OrderElement/Update.cshtml
@model WebAutopark.Models.OrderElementViewModel
@{
    ViewData["Title"] = "Update OrderElement";
}

<h2>@ViewData["Title"].</h2>


<form asp-action="Update" asp-controller="OrderElement">
    <div>
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <input type="hidden" asp-for="OrderElementId" />
        <input type="hidden" asp-for="OrderId" />
        <div class="form-group">
            <label asp-for="DetailId"></label>
            <select class="form-select custom-select" asp-for="DetailId">
                @foreach (var detail in ViewBag.Details)
                {
                    <option value="@detail.DetailId">@detail.DetailName</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label asp-for="Quantity"></label>
            <input asp-for="Quantity" class="form-control form-control-sm"/>
            <span asp-validation-for="Quantity" />
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-outline-secondary" />
        </div>
    </div>
</form>

<div>
    <a asp-controller="OrderElement" asp-action="Index" asp-route-orderId="@Model.OrderId">Back to the order elements</a>
</div>