WebAutopark/Models/DetailViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAutopark.Models
{
    public class DetailViewModel
    {
        [Required]
        public int DetailId { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "DetailName length must be 3-50 characters")]
        public string DetailName { get; set; }
    }
}

WebAutopark/Controllers/DetailController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using WebAutopark.BusinessLogicLayer.DataTransferObjects;
using WebAutopark.BusinessLogicLayer.Interfaces;
using WebAutopark.Models;

namespace WebAutopark.Controllers
{
    public class DetailController : Controller
    {
        private readonly IDataService<DetailDto> _detailDtoService;
        private readonly IMapper _mapper;

        public DetailController(IDataService<DetailDto> dtoService, IMapper mapper)
        {
            _detailDtoService = dtoService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var detailsDto = await _detailDtoService.GetAll();
            var detailsView = _mapper.Map<List<DetailViewModel>>(detailsDto);
            return View(detailsView);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(DetailViewModel detailViewModel)
        {
            if (ModelState.IsValid)
            {
                var detailDto = _mapper.Map<DetailDto>(detailViewModel);
                await _detailDtoService.Create(detailDto);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var detailDto = await _detailDtoService.GetById(id);

            if (detailDto != null)
            {
                var detailView = _mapper.Map<DetailViewModel>(detailDto);
                return View(detailView);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DetailViewModel detailViewModel)
        {
            if (ModelState.IsValid)
            {
                var detailDto = _mapper.Map<DetailDto>(detailViewModel);
                await _detailDtoService.Update(detailDto);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var detailDto = await _detailDtoService.GetById(id);

            if (detailDto != null)
            {
                var detailView = _mapper.Map<DetailViewModel>(detailDto);
                return View(detailView);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _detailDtoService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebAutopark/Controllers/VehicleController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using WebAutopark.BusinessLogicLayer.DataTransferObjects;
using WebAutopark.BusinessLogicLayer.Interfaces;
using WebAutopark.Models;
using System;
using System.Linq;
using WebAutopark.Core.Enums;


namespace WebAutopark.Controllers
{
    public class VehicleController : Controller
    {
        private readonly IVehicleService _vehicleDtoService;
        private readonly IDataService<VehicleTypeDto> _vehicleTypeDtoService;
        private readonly IMapper _mapper;

        public VehicleController(IVehicleService vehicleDtoService,
                                 IDataService<VehicleTypeDto> vehicleTypeDtoService,
                                 IMapper mapper)
        {
            _vehicleDtoService = vehicleDtoService;
            _vehicleTypeDtoService = vehicleTypeDtoService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchName, SortOrder sortOrder)
        {
            ViewBag.SortByModel = sortOrder == SortOrder.ModelAsc ? SortOrder.ModelDesc : SortOrder.ModelAsc;
            ViewBag.SortByMileage = sortOrder == SortOrder.MileageAsc ? SortOrder.MileageDesc : SortOrder.MileageAsc;
            ViewBag.SortByType = sortOrder == SortOrder.TypeAsc ? SortOrder.TypeDesc : SortOrder.TypeAsc;

            ViewBag.CurrentSearchName = searchName;

            var vehiclesDto = await _vehicleDtoService.GetAll(sortOrder);

            if (!String.IsNullOrEmpty(searchName))
            {
                vehiclesDto = vehiclesDto.Where(v => v.Model
                    .Contains(searchName, StringComparison.OrdinalIgnoreCase));
            }

            var vehiclesView = _mapper.Map<List<VehicleViewModel>>(vehiclesDto);
            return View(vehiclesView);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Colors = Enum.GetValues(typeof(Color)).Cast<Color>();
            ViewBag.Types = await _vehicleTypeDtoService.GetAll();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(VehicleViewModel vehicleViewModel)
        {
            if (ModelState.IsValid)
            {
                var vehicleDto = _mapper.Map<VehicleDto>(vehicleViewModel);
                await _vehicleDtoService.Create(vehicleDto);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var vehicleDto = await _vehicleDtoService.GetById(id);

            if (vehicleDto != null)
            {
                var vehicleView = _mapper.Map<VehicleViewModel>(vehicleDto);
                return View(vehicleView);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _vehicleDtoService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var vehicleDto = await _vehicleDtoService.GetById(id);

            if (vehicleDto != null)
            {
                ViewBag.Colors = Enum.GetValues(typeof(Color))
                                     .Cast<Color>();

                ViewBag.Types = await _vehicleTypeDtoService.GetAll();
                var vehicleView = _mapper.Map<VehicleViewModel>(vehicleDto);
                return View(vehicleView);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VehicleViewModel vehicleViewModel)
        {
            if (ModelState.IsValid)
            {
                var vehicleDto = _mapper.Map<VehicleDto>(vehicleViewModel);
                await _vehicleDtoService.Update(vehicleDto);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Information(int id)
        {
            var vehicleDto = await _vehicleDtoService.GetById(id);
            var vehicleView = _mapper.Map<VehicleViewModel>(vehicleDto);

            return View(vehicleView);
        }
    }
}

WebAutopark/Views/Detail/ConfirmDelete.cshtml
    @model WebAutopark.Models.DetailViewModel
@{
    ViewData["Title"] = "Delete Detail";
}
<h2>@ViewBag.Title</h2>
<div>
    <dl class="dl-horizontal">
        <dt>ID</dt>
        <dd>
            @Model.DetailId
        </dd>

        <dt>Name</dt>
        <dd>
            @Model.DetailName
        </dd>
    </dl>

    <div>
        <form asp-controller="Detail" asp-action="Delete" asp-route-id="@Model.DetailId" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Delete" />
            </div>
        </form>
    </div>
</div>

WebAutopark/Views/Detail/Create.cshtml
@model WebAutopark.Models.DetailViewModel

@{
    ViewData["Title"] = "New Detail";
}
<h2>@ViewData["Title"]</h2>

<form asp-action="Create" asp-controller="Detail">
    <div>
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="DetailName"></label>
            <input asp-for="DetailName" class="form-control form-control-sm" />
            <span asp-validation-for="DetailName" />
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-outline-secondary" />
        </div>
    </div>
</form>

<div>
    <a asp-controller="Vehicle" asp-action="Index">Back to the list</a>
</div>

WebAutopark/Views/Detail/Delete.cshtml
@model WebAutopark.Models.DetailViewModel
@{
    ViewData["Title"] = "Delete Detail";
}
<h2>@ViewBag.Title</h2>
<div>
    <dl class="dl-horizontal">
        <dt>ID</dt>
        <dd>
            @Model.DetailId
        </dd>

        <dt>Name</dt>
        <dd>
            @Model.DetailName
        </dd>
    </dl>

    <div>
        <form asp-controller="Detail" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Delete" />
            </div>
        </form>
    </div>
</div>

WebAutopark/Views/Detail/Edit.cshtml
@model WebAutopark.Models.DetailViewModel;
@{
    ViewData["Title"] = "Update detail";
}

<h2>@ViewData["Title"].</h2>

<form asp-action="Edit" asp-controller="Detail">
    <div>
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <input type="hidden" asp-for="DetailId" />
        <div class="form-group">
            <label asp-for="DetailName"></label>
            <input asp-for="DetailName" class="form-control form-control-sm" />
            <span asp-validation-for="DetailName" />
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-outline-secondary" />
        </div>
    </div>
</form>

<div>
    <a asp-controller="Detail" asp-action="Index">Back to the list</a>
</div>

WebAutopark/Views/Detail/Index.cshtml
@model IEnumerable<WebAutopark.Models.DetailViewModel>

@{
    ViewData["Title"] = "ViewDetails";
}

<hr />
<h4 class="text-center my-1">Details list</h4>
<hr />
<table class="table table-striped table-borderless table-sm">
    <thead class="thead-light">
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.DetailId
                </td>
                <td>
                    @item.DetailName
                </td>
                <td>
                    <a asp-controller="Detail" asp-action="Edit" asp-route-id="@item.DetailId">Udpate</a> |
                    <a asp-controller="Detail" asp-action="ConfirmDelete" asp-route-id="@item.DetailId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<p>
    <a asp-controller="Detail" asp-action="Create">Add</a>
</p>